name: network_base
description: A new Flutter package project.
version: 2.0.0
homepage: https://github.com/cassiomeira12/network_base

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 5.3.2
  graphql: 5.1.3
  pretty_json: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
